<a href="https://colab.research.google.com/github/luanakwon/GreatBarrierReef/blob/main/GBR_f2score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Download dataset from kaggle api
kaggle  
https://www.kaggle.com/c/tensorflow-great-barrier-reef/data  

kaggle API usage  
https://colab.research.google.com/github/corrieann/kaggle/blob/master/kaggle_api_in_colab.ipynb

In [1]:
!pip install kaggle
!pip install --upgrade --force-reinstall --no-deps kaggle

     |████████████████████████████████| 58 kB 4.6 MB/s 
  Created wheel for kaggle: filename=kaggle-1.5.12-py3-none-any.whl size=73051 sha256=0596634e5ef41a13e7facc0f2ea644563efcee2c8efe5bafa5747ca0d17a292e
  Stored in directory: /root/.cache/pip/wheels/62/d6/58/5853130f941e75b2177d281eb7e44b4a98ed46dd155f556dc5
Successfully built kaggle
  Attempting uninstall: kaggle
    Found existing installation: kaggle 1.5.12
    Uninstalling kaggle-1.5.12:
      Successfully uninstalled kaggle-1.5.12


In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  
# Then move kaggle.json into the folder where the API expects to find it.
!mkdir -p ~/.kaggle/ && mv kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json

Saving kaggle.json to kaggle.json
User uploaded file "kaggle.json" with length 68 bytes


In [3]:
!kaggle competitions download -c tensorflow-great-barrier-reef

100% 14.2G/14.2G [01:26<00:00, 204MB/s]
100% 14.2G/14.2G [01:26<00:00, 176MB/s]


In [4]:
!unzip -q /content/tensorflow-great-barrier-reef.zip 

# Organize dataset

In [5]:
# get train.csv
import pandas as pd

df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [6]:
# create hierarchy
import os

for f2 in 'images', 'labels':
  os.makedirs(f'/content/Datasets/val/{f2}')

In [7]:
def annotation2YoloFormat(_annotation, width=1280, height=720):
  out= ''
  bboxes = eval(_annotation)
  for x in bboxes:
    x = list(x.values())
    out += '0 %.6f %.6f %.6f %.6f\n'%(
      max(0,min(1,(x[0]+x[2]/2)/width)),
      max(0,min(1,(x[1]+x[3]/2)/height)),
      max(0,min(1,x[2]/width)),
      max(0,min(1,x[3]/height))
    )
  return out.lstrip()

In [8]:
import random
import shutil

VAL_DIRECTORY = "/content/Datasets/val"

random.seed(10)

df = df_train
for index, row in df.iterrows():
  path_from = f'/content/train_images/video_{row.video_id}/{row.video_frame}.jpg'
  path_to = os.path.join(VAL_DIRECTORY,f'images/{row.image_id}.jpg')
  lb_path_to = os.path.join(VAL_DIRECTORY,f'labels/{row.image_id}.txt')

  random_value = random.random()
  if random_value < .64:
    # if row.annotations != '[]':
    #   shutil.move(row.image_path, f'train/images/{row.image_id}.jpg')
    #   with open(f'train/labels/{row.image_id}.txt', 'w') as f:
    #     for i in row.bbox:
    #       f.write("0 {} {} {} {}\n".format(*i))
    continue
  else:
    shutil.move(path_from, path_to)
    if row.annotations != '[]':
      with open(lb_path_to, 'w') as f:
        f.write(annotation2YoloFormat(row.annotations))

# Inference on Validation dataset

In [9]:
import torch
import cv2
import numpy as np

In [10]:
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -qr requirements.txt  # install

from yolov5 import utils
display = utils.notebook_init()  # checks

YOLOv5 🚀 v6.0-248-gcb2ad9f torch 1.10.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)


Setup complete ✅ (2 CPUs, 12.7 GB RAM, 70.7/166.8 GB disk)


In [11]:
def load_model(ckpt_path, conf=0.25, iou=0.50):
  model = torch.hub.load('/content/yolov5',
                          'custom',
                          path=ckpt_path,
                          source='local',
                          force_reload=True)  # local repo
  model.conf = conf  # NMS confidence threshold
  model.iou  = iou  # NMS IoU threshold
  model.classes = None   # (optional list) filter by class, i.e. = [0, 15, 16] for persons, cats and dogs
  model.multi_label = False  # NMS multiple labels per box
  model.max_det = 1000  # maximum number of detections per image
  return model

In [12]:
def predict(model, img, size=768, augment=False):
  height, width = img.shape[:2]
  results = model(img, size=size, augment=augment)  # custom inference size
  preds   = results.pandas().xyxy[0]
  bboxes  = preds[['xmin','ymin','xmax','ymax']].values
  if len(bboxes):
    bboxes[:,2:] -= bboxes[:,:2]
    bboxes  = bboxes.astype(int)
    confs   = preds.confidence.values
    return bboxes, confs
  else:
    return [],[]

def format_prediction(bboxes, confs):
    annot = ''
    if len(bboxes)>0:
        for idx in range(len(bboxes)):
            xmin, ymin, w, h = bboxes[idx]
            conf             = confs[idx]
            annot += f'{conf} {xmin} {ymin} {w} {h}'
            annot +=' '
        annot = annot.strip(' ')
    return annot

In [16]:
# calculate IoU
# pred = (x, y, width, height)
# label = (x, y, width, height)
def getIoU(pred, label):

  area_label = label[2] * label[3]
  area_predict = pred[2] * pred[3]
  area_of_overlap = max(0,min(label[0]+label[2]*0.5, pred[0]+pred[2]*0.5)\
                  - max(label[0]-label[2]*0.5, pred[0]-pred[2]*0.5))\
                  * \
                  max(0,min(label[1]+label[3]*0.5, pred[1]+pred[3]*0.5) \
                  - max(label[1]-label[3]*0.5, pred[1]-pred[3]*0.5))
  area_of_union = area_label + area_predict - area_of_overlap
  return area_of_overlap / area_of_union

def getConfusion(bboxes, confis, labels, iou_thres,
                 conf_min=0, conf_max=1, conf_step=0.1):
  # list of [x,y,w,h,conf]
  b4c1 = [[*b,c] for b, c in zip(bboxes,confis)]
  b4c1.sort(key=lambda x : x[4]) # sort in ascending order
  # confusion matrix [conf_thres,tp,fp,fn]
  cm = np.zeros((int((conf_max-conf_min)/conf_step)+1,4))
  for i, c in enumerate(cm):
    c[0] = conf_min+i*conf_step
  # make confusion matrix for all conf thres
  for conf_idx in range(cm.shape[0]):
    lbs = labels.copy()
    bc = b4c1.copy()
    for i, x in enumerate(bc):
      if x[4] > cm[conf_idx,0]:
        bc = bc[i:]
        break
    
    trues = len(lbs)
    # find pred-label match
    for sub_box in reversed(bc):
      for l in lbs:
        if getIoU(sub_box[:-1],l) > iou_thres:
          cm[conf_idx,1] += 1
          bc.remove(sub_box)
          lbs.remove(l)
          break
    # remains are False Positive and False Negative each
    cm[conf_idx,2] = len(bc)
    cm[conf_idx,3] = len(lbs)
  
    
  return cm[:,1:]

In [19]:
IMG_SIZE = 2048
CONF_MIN = 0.1
CONF_MAX = 0.8
CONF_STEP = 0.1
VAL_DIRECTORY = '/content/Datasets/val'
LEN_VAL_DIR = len(os.listdir(f'{VAL_DIRECTORY}/images'))
conf_steps = int((CONF_MAX-CONF_MIN)/CONF_STEP)+1

my_model = load_model('/content/best.pt', conf=CONF_MIN, iou=0.3)
m_confusions = np.zeros((11,conf_steps,3)) 

for idx,img_f in enumerate(os.listdir(f'{VAL_DIRECTORY}/images')):
  if idx > 100:
    break
  
  path = f'{VAL_DIRECTORY}/images/{img_f}'
  print(f'\r[{idx}/{LEN_VAL_DIR}]{path}',end='\t\t')
  img = cv2.imread(path)[...,::-1]
  annot = eval(df_train[df_train.image_id == img_f[:-4]].annotations.item())
  # my model
  bboxes, confis = predict(my_model, img, size=2048, augment=True)

  for iou_idx in range(11): # iou thres from 0.3 to 0.8 step 0.05
    iou_thres = 0.05*iou_idx+0.3
    labels = [list(x.values()) for x in annot]
    m_confusions[iou_idx] += getConfusion(bboxes, confis, labels, iou_thres,
                                          CONF_MIN,CONF_MAX,CONF_STEP)

       

print()
# result - my model
confusions = m_confusions
# print(confusions)
# prevent zero division
no_tp = confusions[:,:,0] == 0
confusions[:,:,0] += no_tp

precisions = confusions[:,:,0]/(confusions[:,:,0]+confusions[:,:,1])
recalls = confusions[:,:,0]/(confusions[:,:,0]+confusions[:,:,2])
f2s = (5*precisions*recalls)/(4*precisions+recalls)

f2s *= np.logical_not(no_tp)
for i in range(conf_steps):
  print(CONF_MIN+CONF_STEP*i, end='  ')
print()
print(f2s)
print(np.mean(f2s,axis=(0)))

requirements: PyYAML>=5.3.1 not found and is required by YOLOv5, attempting auto-update...

requirements: 1 package updated per /content/yolov5/requirements.txt
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

YOLOv5 🚀 v6.0-248-gcb2ad9f torch 1.10.0+cu111 CUDA:0 (Tesla P100-PCIE-16GB, 16281MiB)

Fusing layers... 
Model Summary: 213 layers, 7012822 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


[100/8308]/content/Datasets/val/images/2-6219.jpg		
0.1  0.2  0.30000000000000004  0.4  0.5  0.6  0.7000000000000001  0.8  
[[    0.19011     0.28027     0.28698     0.20073     0.14634     0.12178       0.125     0.11676]
 [    0.18378     0.26906     0.27594     0.19161     0.13821     0.11461     0.11806     0.10989]
 [    0.18378     0.26906     0.27594     0.19161     0.13821     0.11461     0.11806     0.10989]
 [    0.18378     0.26906     0.27594     0.19161     0.13821     0.11461     0.11806     0.10989]
 [     0.1711     0.25785      0.2649     0.18248     0.13008     0.10745     0.11111     0.10302]
 [    0.15843     0.23543     0.24283     0.16423     0.11382    0.093123    0.097222    0.089286]
 [    0.14575     0.22422     0.23179     0.15511     0.10569     0.08596    0.090278    0.082418]
 [    0.12041     0.19058     0.19868     0.13686    0.097561    0.078797    0.076389    0.061813]
 [   0.095057     0.14574     0.15453     0.10949    0.081301     0.06447      0.062